### PR TITLE
symfony/http-foundation 5.0

### PR DESCRIPTION
**Pull request by recca0120**

### CODE REVIEW

**Comment by decadence** [comment]
Same problem with botman/driver-telegram

**Comment by recca0120** [comment]
@decadence 
what is the problem ?
Could you show me more information ?

**Comment by AntonLugtenburg** [comment]
It fails because the driver requires botman itself which requires symfony 4

**Comment by decadence** [comment]
@recca0120 BotMan and Telegram drivers fail on composer install with Laravel 7 because they don't support Symfony 5 packages.

**Comment by AntonLugtenburg** [comment]
Thx

**Comment by decadence** [comment]
When we can get this as a release? Laravel 7 app still can't install BotMan.

**Comment by AntonLugtenburg** [comment]
Pull it from Github...

add this to composer.json:

 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/botman/botman"
        }
    ],

**Comment by decadence** [comment]
Maybe @mpociot just tag a new version.

**Comment by decadence** [comment]
Bump @mpociot

**Comment by willianmaria** [comment]
Hi, @mpociot can you apply this in composer please? I can't install botman in Laravel 7. :(

**Comment by decadence** [comment]
I end up with @AntonLugtenburg solution and dev-master version for Botman.

**Comment by willianmaria** [comment]
> I end up with @AntonLugtenburg solution and dev-master version for Botman.

Can you share your `compose.json` edit?

**Comment by decadence** [comment]
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/botman/botman"
        }
    ]

Then require
"botman/botman": "2.0.x-dev"

**Comment by willianmaria** [comment]
> "repositories": [
> {
> "type": "vcs",
> "url": "https://github.com/botman/botman"
> }
> ]
> 
> Then require
> "botman/botman": "2.0.x-dev"

Thanks! 
I found another way to solve my problem too: `composer require botman/driver-web` 
This way botman/botman is installed and I can use the web driver also.

**Comment by nikitabuida** [comment]
Your solution fixes botman/driver-web, but doesn't fix botman/driver-slack at all because it requires botman 2.2 or dev-master

**Pull request merged**
