### PR TITLE
Feature/add api driver

### PR DESCRIPTION
**Pull request by christophrumpel**
So this is the first draft of a working API driver. It should state why I think it could benefit the library and point out some of the current problems. I hope we can together figure out how it would fit to BotMan and how to solve the remaining problems.

**Usecase:**

We are building right now a chatbot for an insurance company and it will be on Facebook and on their website. We are using BotMan and it works great for FB. We also wanted to use it for the website, this is why I built this ApiDriver. We will see much more chatbots on websites too in the future and this is why I think an API would make total sense.

**How it works:**
It is receiving data, like the other drivers, over the webhook. For example this JSON:
```json
{
	"driver": "api",
	"message": "hello",
	"userId": "12345"
}
```

Through the driver property it will match the ApiDriver. And of course there is a `message` and a `userId` to save the user.

This could return (depending on your `hears` method, JSON as well:

```json
{
	"status": 200,
	"messages": [
		{
			"type": "text",
			"text": "hello you too"
		}
	]
}
```

**Decisions**
First decision I had to make was about the `return` of the driver. The other drivers are sending separate requests to their messenger back. I did not want to do that because of these reasons:

- websites are not like messenger platforms
- every website will be different, as well as the frontend
- every website would need an API to handle the returns form the ApiDriver

This why I decided `not` to send requests, and just response to the initial request with the data. This would give websites the possibility to handle their chatbot logic (frontend, backend) as they like and BotMan does not need to know about how the websites work. BotMan just provides an API everyone can use.

**Problems:**
With this decision there is one big problem. In BotMan you can send multiple replies like: 
```php
$this->say('Nice to meet you '.$this->firstname);
$this->askEmail();
```

With the FacebookDriver this would send two request to the FB api, but with the ApiDriver we just have one return and this is a problem, because both `say` and `askEmail` are treated separately without knowing if there are more grouped messages coming.

**Hack**
To solve that I am using right now a little hack.
```php
$botman->hears('hello', function(BotMan $botMan) {
           $botMan->reply('hey');
           $botMan->reply('hello you too##end##');
});
```
I am adding a `tag` like `##end##` to the last of the "grouped messages". The ApiDriver will store all messages in the cache, until a message has this end. Then it will grab all the messages and send them together as one response. (of course clearing the tag out before)
```JSON
{
	"status": 200,
	"messages": [
		{
			"type": "text",
			"text": "hey"
		},
		{
			"type": "text",
			"text": "hello you too"
		}
	]
}
````
This was the only way I could think of of to easily make this work. As mentioned this is working perfectly in production for me, but maybe it is not the best solution for BotMan. Here I could need help.

**Templates:**
Of course the API needs to handle different templates too, because your website needs to know if it should show buttons or an image etc.
So a question like this:
```php
$botman->hears('hello', function(BotMan $botMan) {
            $question = Question::create('What do want to do?##end##')
                ->addButton(Button::create('Stay'))
                ->addButton(Button::create('Leave'));
           $botMan->reply($question);
        });
```
would get a response like this:
```json
{
	"status": 200,
	"messages": [
		{
			"type": "buttons",
			"text": "What do want to do?",
			"buttons": [
				{
					"text": "Stay",
					"keyword": null,
					"imageUrl": null
				},
				{
					"text": "Leave",
					"keyword": null,
					"imageUrl": null
				}
			]
		}
	]
}
Then the website can decide how to use this information.
```

**Missing:**

Big parts I see missing right now are:

- Solution for the `tag problem`
- Not all templates are covered yet (there are lots of them 😄)
- tests are missing (wanted to talk about the other stuff first)

So it would be great to get some feedback and I hope we can  bring a cool new driver to BotMan :-)

PS: It is great for testing too :-)

### CODE REVIEW

**Comment by ribb3r** [comment]
Great feature 👍

**Comment by christophrumpel** [comment]
Thx, still working on some little issues but hope to finish it soon.

**Comment by christophrumpel** [comment]
I just implemented the handling of all the templates with the API driver. I tried to change the field names to get a overall similar response.

As mentioned I added the `afterMessagesHandled` which is called from every driver. This is why I needed to add the method to all drivers and I guess this i why the codevoc fails right? Is there a better solution for that? Don't think it is important to test am empty method?

**Comment by mpociot** [comment]
This PR found a new home at https://github.com/botman/driver-web

Thanks again for your hard work on the project and the PR! :)

**Pull request closed without merging**
