### PR TITLE
add some Extras for showing multiple responses and context from Dialogflow

### PR DESCRIPTION
**Pull request by cendekia**
It also differentiates between text response and payload response
and I also added extras to get the `context` from DialogFlow

### CODE REVIEW

**Comment by christophrumpel** [comment]
Thanks. What are custom responses? Please also check the style errors and update the tests, see travis-ci errors.

**Comment by cendekia** [comment]
> Thanks. What are custom responses? Please also check the style errors and update the tests, see travis-ci errors.

There are two types of `intents` responses, `text response` and `custom payload response`. I'm having trouble building the unit testing, not really expert on this :(
Maybe somebody can help me with this 💯

**Comment by cendekia** [comment]
@christophrumpel All checks have passed

**Comment by christophrumpel** [comment]
Thanks. @cendekia

**Comment by christophrumpel** [comment]
In a botman version 3 it would be great if we could get rid of the ApiAi middleware and rename all the the DialogFlow field better.

**Comment by cendekia** [comment]
> In a botman version 3 it would be great if we could get rid of the ApiAi middleware and rename all the the DialogFlow field better.

Yes, it would be better, I would love to do the PR for it

**Comment by christophrumpel** [comment]
Great, let's talk about it when there is a botman version 3. Not planned yet.

**Comment by cendekia** [comment]
Cool

**Pull request merged**
