### PR TITLE
Fix type of Curl::prepareRequest()

### PR DESCRIPTION
**Pull request by sasha-x**
Remove static keyword.

### CODE REVIEW

**Comment by sasha-ch** [comment]
Not sure why tests fail.

**Comment by sasha-ch** [comment]
Any chance?

**Comment by feralheart** [comment]
Hi @sasha-x ,
Can you describe what does it fix in the project when it will be merged?
And is there any possible breaks because of this?

**Comment by sasha-x** [comment]
As I rememder, method was declared as static but use in object context. 
So I can't correctly override it in my class.
I fix it.
At the moment pr was opened new code works ok for me.

**Comment by feralheart** [comment]
I see, thank you

**Pull request merged**
