### PR TITLE
Specify Slack Verification Token

### PR DESCRIPTION
**Pull request by marktopper**

### CODE REVIEW

**Comment by a-komarev** [comment]
Maybe it will be better to have separate method for each service verification? Otherwise later it will look like:

```php
$botman->verifyServices(null, null, null, null, 'my-secret');
```

Something like this one:
```php
$botman->verifyFacebookService('my-secret');
$botman->verifySlackService('my-secret');
```

**Comment by mpociot** [comment]
Yes, was thinking the same.
Or maybe just pass an array with all the verification tokens available?

**Comment by a-komarev** [comment]
Both of the cases could be implemented:

```php
$botman->verifySlackService('my-secret');

public function verifySlackService($secret)
{
    return $this->verifyServices(['slack' => $secret]);
}
```

Or encapsulate verification in separate class.

**Comment by marktopper** [comment]
Will go ahead and do that. 👍

**Comment by mpociot** [comment]
I don't really like the fact that this will break all previous versions of BotMan

**Comment by marktopper** [comment]
Me neither, however the current code was not created for handling that many verification codes.

I could implement a fallback to the original `$facebookVerfication` and `$weChatVerification` in case that an array is not sent with the `verifyServices` method.

Should I do the implementation?

**Comment by mpociot** [comment]
Yes, please implement a fallback - I'll then mark the string method as deprecated for future releases. 

Please also update the test(s).

**Comment by marktopper** [comment]
I removed the test I added for testing Slack verification.
Since I can not figure out how to mock a payload.

**Pull request closed without merging**
